[install]
minimumReleaseAge = 172800
minimumReleaseAgeExcludes = [
  "@pierre/diffs",
  "@pierre/themes",
  "@pierre/trees",
  "@playwright/mcp",
  "@types/bun",
  "@types/bun",
  "@typescript/native-preview",
  "@typescript/native-preview-darwin-arm64",
  "chrome-devtools-mcp",
  "oxfmt",
  "oxlint",
  "oxlint-tsgolint",
  "typescript"
]
