[install]
minimumReleaseAge = 172800
minimumReleaseAgeExcludes = [
  "@amadeusdemarzi/git-gw",
  "@mozilla/firefox-devtools-mcp-moz",
  "@pierre/diffs",
  "@pierre/themes",
  "@pierre/trees",
  "@playwright/mcp",
  "@types/bun",
  "@types/bun",
  "@typescript/native-preview",
  "@typescript/native-preview-darwin-arm64",
  "chrome-devtools-mcp",
  "oxfmt",
  "oxlint",
  "oxlint-plugin-react-doctor",
  "oxlint-tsgolint",
  "playwright",
  "playwright-core",
  "react-doctor",
  "safari-mcp",
  "typescript"
]
