[install]
minimumReleaseAge = 172800
minimumReleaseAgeExcludes = [
  "@types/bun",
  "typescript",
  "@pierre/diffs",
  "@pierre/themes",
  "@pierre/trees",
  "@typescript/native-preview",
  "oxfmt",
  "oxlint",
  "oxlint-tsgolint",
  "@types/bun",
  "@typescript/native-preview-darwin-arm64"
]
